#ifndef AP_MEMORY_DOORS_H
#define AP_MEMORY_DOORS_H

enum DOORS_COST {
    DINO_DOMAIN = 0,
    SNOWFLAKE_MOUNTAIN,
    SHERBET_ISLAND,
    DRAGON_FOREST,
    FUTURE_FUN_LAND,

    ANCIENT_LAKE,
    ANCIENT_LAKE_DOOR2,
    FOSSIL_CANYON,
    FOSSIL_CANYON_DOOR2,
    JUNGLE_FALLS,
    JUNGLE_FALLS_DOOR2,
    HOT_TOP_VOLCANO,
    HOT_TOP_VOLCANO_DOOR2,

    EVERFROST_PEAK,
    EVERFROST_PEAK_DOOR2,
    WALRUS_COVE,
    WALRUS_COVE_DOOR2,
    SNOWBALL_VALLEY,
    SNOWBALL_VALLEY_DOOR2,
    FROSTY_VILLAGE,
    FROSTY_VILLAGE_DOOR2,

    WHALE_BAY,
    WHALE_BAY_DOOR2,
    CRESCENT_ISLAND,
    CRESCENT_ISLAND_DOOR2,
    PIRATE_LAGOON,
    PIRATE_LAGOON_DOOR2,
    TREASURE_CAVES,
    TREASURE_CAVES_DOOR2,

    WINDMILL_PLAINS,
    WINDMILL_PLAINS_DOOR2,
    GREENWOOD_VILLAGE,
    GREENWOOD_VILLAGE_DOOR2,
    BOULDER_CANYON,
    BOULDER_CANYON_DOOR2,
    HAUNTED_WOODS,
    HAUNTED_WOODS_DOOR2,

    SPACEDUST_VALLEY,
    SPACEDUST_VALLEY_DOOR2,
    DARKMOON_CAVERNS,
    DARKMOON_CAVERNS_DOOR2,
    SPACEPORT_ALPHA,
    SPACEPORT_ALPHA_DOOR2,
    STAR_CITY,
    STAR_CITY_DOOR2,

    AP_MAX_DOORS
};

#endif