#ifndef AP_MEMORY_TRACKS_H
#define AP_MEMORY_TRACKS_H
    enum TRACKS {
        TRACK_NONE = 0,
        TRACK_ANCIENT_LAKE,
        TRACK_FOSSIL_CANYON,
        TRACK_JUNGLE_FALLS,
        TRACK_HOT_TOP_VOLCANO,

        TRACK_EVERFROST_PEAK,
        TRACK_WALRUS_COVE,
        TRACK_SNOWBALL_VALLEY,
        TRACK_FROSTY_VILLAGE,

        TRACK_WHALE_BAY,
        TRACK_CRESCENT_ISLAND,
        TRACK_PIRATE_LAGOON,
        TRACK_TREASURE_CAVES,

        TRACK_WINDMILL_PLAINS,
        TRACK_GREENWOOD_VILLAGE,
        TRACK_BOULDER_CANYON,
        TRACK_HAUNTED_WOODS,

        TRACK_SPACEDUST_VALLEY,
        TRACK_DARKMOON_CAVERNS,
        TRACK_SPACEPORT_ALPHA,
        TRACK_STAR_CITY,

        AP_MAX_TRACKS
    };
#endif
