#ifndef AP_MEMORY_ITEMS_H
#define AP_MEMORY_ITEMS_H

enum AP_ITEMS {
    AP_TIMBER_ISLAND_BALLOON = 0,
    AP_DINO_DOMAIN_BALLOON,
    AP_SNOWFLAKE_MOUNTAIN_BALLOON,
    AP_SHERBET_ISLAND_BALLOON,
    AP_DRAGON_FOREST_BALLOON,
    AP_FUTURE_FUN_LAND_BALOON,
    AP_FIRE_MOUNTAIN_KEY,
    AP_ICICLE_PYRAMID_KEY,
    AP_DARKWATER_BEACH_KEY,
    AP_SMOKEY_CASTLE_KEY,
    AP_WIZPIG_AMULET_PIECE,
    AP_TT_AMULET_PIECE,
    AP_KART,
    AP_HOVERCAR,
    AP_PLANE,
    AP_MAX_ITEM
};

#endif
